name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH with Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GHCR_PAT
          script: |
            set -e
            cd /home/kirill/desktop/devops
            chmod +x ./deploy.sh
            
            # Передаём секрет в скрипт
            export GHCR_PAT="${{ secrets.GHCR_PAT }}"
            
            ./deploy.sh "ghcr.io/kirilldrs/catty-reminders-app" "${{ github.sha }}"
